# Generated by Django 3.0.7 on 2020-07-08 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始時期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了時期')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='日付')),
                ('part', models.CharField(blank=True, choices=[('胸', '胸'), ('背中', '背中'), ('肩', '肩'), ('腕', '腕'), ('脚', '脚'), ('腹', '腹'), ('全身', '全身'), ('上半身', '上半身'), ('下半身', '下半身')], max_length=50, null=True, verbose_name='部位')),
                ('detail_part', models.CharField(blank=True, max_length=50, null=True, verbose_name='部位詳細')),
                ('routine_delete_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='個別削除数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
