# Generated by Django 3.0.7 on 2020-08-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_bodypart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypart',
            name='part',
            field=models.CharField(blank=True, choices=[('胸', '胸'), ('背中', '背中'), ('肩', '肩'), ('腕', '腕'), ('脚', '脚'), ('腹', '腹'), ('全身', '全身'), ('上半身', '上半身')], max_length=50, null=True, verbose_name='部位'),
        ),
    ]
