# Generated by Django 3.0.7 on 2020-11-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_auto_20200825_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodypart',
            name='image',
        ),
    ]
