# Generated by Django 3.0.7 on 2020-11-17 06:38

from django.db import migrations, models
import routine.models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_remove_bodypart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypart',
            name='part',
            field=models.CharField(blank=True, choices=[('胸', '胸'), ('背中', '背中'), ('肩', '肩'), ('腕', '腕'), ('脚', '脚'), ('腹', '腹'), ('全身', '全身'), ('上半身', '上半身')], max_length=50, null=True, validators=[routine.models.check_part], verbose_name='部位'),
        ),
    ]
