# Generated by Django 3.0.7 on 2020-08-26 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routine', '0003_auto_20200825_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(blank=True, max_length=30, null=True)),
                ('weight_1', models.IntegerField(blank=True, null=True, verbose_name='重量1')),
                ('weight_2', models.IntegerField(blank=True, null=True, verbose_name='重量2')),
                ('weight_3', models.IntegerField(blank=True, null=True, verbose_name='重量3')),
                ('weight_4', models.IntegerField(blank=True, null=True, verbose_name='重量4')),
                ('weight_5', models.IntegerField(blank=True, null=True, verbose_name='重量5')),
                ('weight_6', models.IntegerField(blank=True, null=True, verbose_name='重量6')),
                ('weight_7', models.IntegerField(blank=True, null=True, verbose_name='重量7')),
                ('weight_8', models.IntegerField(blank=True, null=True, verbose_name='重量8')),
                ('weight_9', models.IntegerField(blank=True, null=True, verbose_name='重量9')),
                ('weight_10', models.IntegerField(blank=True, null=True, verbose_name='重量10')),
                ('times_1', models.IntegerField(blank=True, null=True, verbose_name='回数1')),
                ('times_2', models.IntegerField(blank=True, null=True, verbose_name='回数2')),
                ('times_3', models.IntegerField(blank=True, null=True, verbose_name='回数3')),
                ('times_4', models.IntegerField(blank=True, null=True, verbose_name='回数4')),
                ('times_5', models.IntegerField(blank=True, null=True, verbose_name='回数5')),
                ('times_6', models.IntegerField(blank=True, null=True, verbose_name='回数6')),
                ('times_7', models.IntegerField(blank=True, null=True, verbose_name='回数7')),
                ('times_8', models.IntegerField(blank=True, null=True, verbose_name='回数8')),
                ('times_9', models.IntegerField(blank=True, null=True, verbose_name='回数9')),
                ('times_10', models.IntegerField(blank=True, null=True, verbose_name='回数10')),
                ('body_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.BodyPart')),
            ],
        ),
    ]
