# Generated by Django 3.0.7 on 2020-08-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='実行日'),
        ),
    ]
