# Generated by Django 3.0.7 on 2020-07-02 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('女性', '女性'), ('男性', '男性')], max_length=2, verbose_name='性別'),
        ),
    ]
