# Generated by Django 3.0.7 on 2020-09-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
